### ISSUE TITLE
Remove engines specification

### ISSUE THREAD

**Issue by RomainLanz** [arthurvasconcelos/vue-izitoast#16]
Hey 👋 

It seems that you have set specific engines version in the [`package.json`](https://github.com/arthurvasconcelos/vue-izitoast/blob/806faf5e270e2d5bd0ab916c14af226e6acc7ce9/package.json#L36) file.

This break a lot of build for no reason, like people using Node 11.
I believe it would be better to remove them.

Happy to make a PR if you accept those changes.

**Comment by arthurvasconcelos** [comment]
fixed at 98ef214d6b77f2666b878f23735cb07b6b27ed53
