### ISSUE TITLE
Toast is being block by Adblocks (uBlock Origin)

### ISSUE THREAD

**Issue by AnujShr** [arthurvasconcelos/vue-izitoast#21]
I recently noticed that all the alerts are being blocked by my installed adblocker. 
I tried to integrate the package into my project and was not showing any alerts. There were no errors in the console.
But when I went the [iziToast](http://izitoast.marcelodolza.com/) site and found that none of the Examples toast was coming up and decided to turn off the ad-blocker. Then everything was working again. 

Does anyone know any workaround for this?

**Comment by arthurvasconcelos** [comment]
Hi AnujShr this bug was is already raised on iziToast and I think it is on course to be fixed. See here marcelodolza/iziToast#183 marcelodolza/iziToast#185
