### ISSUE TITLE
Support Node 9

### ISSUE THREAD

**Issue by umbrella-kirill-karpov** [arthurvasconcelos/vue-izitoast#3]
Installation with yarn throws an error:

> vue-izitoast@1.1.0: The engine "node" is incompatible with this module. Expected version "^6.11.4 || ^8.7.0".

Node version: 9.2.1

PR: #4

**Comment by umbrella-kirill-karpov** [comment]
PR: #4

**Comment by maaljam** [comment]
Same issue. Node version: v10.0.0

**Comment by appinteractive** [comment]
@arthurvasconcelos PLEASE MERGE #9 !!!

**Comment by arthurvasconcelos** [comment]
Solved in the release:
- https://github.com/arthurvasconcelos/vue-izitoast/releases/tag/1.1.1
- https://www.npmjs.com/package/vue-izitoast/v/1.1.1

Closing the issue.

**Comment by appinteractive** [comment]
Thanks 🙏
