### ISSUE TITLE
error on yarn install

### ISSUE THREAD

**Issue by zangab** [arthurvasconcelos/vue-izitoast#8]
cant install the package with node v9.11.2:
`error vue-izitoast@1.1.0: The engine "node" is incompatible with this module. Expected version "^6.11.4 || ^8.7.0".`

**Comment by jurgenbosch** [comment]
Same issue here. 
You can get around it by using --ignore-enignes (yarn add vue-izitoast --ignore-engines) but it should be fixed in the repo.

**Comment by appinteractive** [comment]
@arthurvasconcelos please merge #9 !!!

**Comment by arthurvasconcelos** [comment]
Related to #3.
Solved.
